---
project:
  name: onica-homework
  owner: sskalnik@sskalnik.com
  regions:
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
tests:
  onica-basic:
    template: ./templates/ec2-cloudformation.yaml
    regions:
      - us-west-1

